### ISSUE TITLE
transcript not available. (EOF) erros

### ISSUE THREAD

**Issue by khalid75** [danielmiessler/Fabric#1638]
When i run -y I receive "transcript not available. (EOF)" error, any feedback

❯ fabric -y "https://youtu.be/UzRItargdgQ?si=zokketrDGwXcyJqT" -sp extract_wisdom
transcript not available. (EOF)

**Comment by AnthoneyY** [comment]
I also meet this problem. 
I upgrade fabric and yt-dlp to the latest version. 

the error 
(fabric)>yt https://www.youtube.com/watch?v=xtzLbmzzM6g
{
  "comments": null,
  "duration": 6,
  "transcript": "Transcript not available. (transcript not found)"
}

fabric --version
v1.4.29-8445b6a

**Comment by ksylvan** [comment]
@khalid75 Please use the "Bug" Issue template in the future so you can provide the needed information:

- What OS are you using? (please provide the following details.)
  - If macOS, paste the output of `sw_vers`
  - if Linux, paste the output of: `uname -a` or `cat /etc/os-release`
  - If windows, paste the output of `vers`

- How did you install Fabric?
    - Release Binary - Windows
    - Release Binary - macOS (arm64)
    - Release Binary - macOS (amd64)
    - Release Binary - Linux (amd64)
    - Release Binary - Linux (arm64)
    - Package Manager - Homebrew (macOS)
    - Package Manager - AUR (Arch Linux)
    - From Source
    - Other

In addition, you must make sure that `yt-dlp` is installed and is the current latest version.
If you installed it.

From what you showed above, your Fabric version is very old. Please update to the latest version (as of this writing it is `v1.4.261`) and make sure you have `yt-dlp` installed.

I am closing this issue; feel free to reopen it if you can't resolve this by updating your Fabric version.

**Comment by ksylvan** [comment]
@khalid75 Checking in here. Did you do as I suggested? Is it working for you now?

**Comment by AnthoneyY** [comment]
@ksylvan 
Hello, ksylvan. I still got stuck on this problem.

My os is Windows, Microsoft Windows [ver 10.0.22631.4037]. 

I installed the fabric when it changed from Python to Go in the November 2024.

In the fabric folder I cloned via git, the fabric version is v1.4.29-8445b6a. In other folders, it is v1.4.31. My yt-dlp version is 2025.06.30.

Please help me with it.

**Comment by ksylvan** [comment]
@AnthoneyY @khalid75 

You need to install the latest Fabric. The fabric must be installed as of today, not as of November 2024.

https://github.com/danielmiessler/Fabric?tab=readme-ov-file#installation

Unless you are planning to do some development on Fabric itself, you can delete all those cloned fabric folders (with old versions).

**Comment by ksylvan** [comment]
@AnthoneyY @khalid75 Is this fixed now?

**Comment by AnthoneyY** [comment]
@ksylvan 
I‘m in China, I'll try it today.

Thanks very much.

**Comment by AnthoneyY** [comment]
@ksylvan 
I'm sorry to bother you at night.

I installed the latest version from source,  'go install github.com/danielmiessler/fabric/cmd/fabric@latest'.
Then I cleared the old version of the fabric in C:\Users\Joey\fabric\fabric.exe.
Now I have only one fabric.exe in the C:\Users\Joey\go\bin\fabric.exe

And now the version of my fabric is v1.4.263, it still can't get the transcript.

Microsoft Windows [ver 10.0.22631.4037].
yt-dlp version is 2025.06.30.

Thanks for your time on this new bird question.

**Comment by khalid75** [comment]
@ksylvan Thanks for the support and sure next time i will use the template
 
Those are my information 👍
 ❯ fabric --version
v1.4.293
❯ sw_vers
ProductName:		macOS
ProductVersion:		15.6
BuildVersion:		24G84
❯ yt-dlp --version
2025.08.11
Source:  go install **github.com/danielmiessler/fabric/cmd/fabric@latest

**Current Status** 
❯ yt "https://youtu.be/n7iT5r0Sl_Y?si=48DTr9t4QOxpkhl-"
no VTT files found in directory

❯ fabric -yt "https://youtu.be/n7iT5r0Sl_Y?si=48DTr9t4QOxpkhl-" -sp extract_wisdom
invalid YouTube URL, can't get video or playlist ID: 't'

❯ fabric -yt "https://youtu.be/n7iT5r0Sl_Y" -sp extract_wisdom
invalid YouTube URL, can't get video or playlist ID: '

❯ fabric -yt "https://www.youtube.com/watch?v=aR6X1jDQk5o" -sp extract_wisdom
invalid YouTube URL, can't get video or playlist ID: 't'
❯ yt "https://www.youtube.com/watch?v=aR6X1jDQk5o"
no VTT files found in directory
